# Generated by Django 5.1.4 on 2024-12-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belief_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beliefnetworkdocument',
            name='term_significance',
        ),
        migrations.RemoveField(
            model_name='beliefnetworkdocument',
            name='terms',
        ),
    ]
